name: Generate app installation access token
description: Creates an installation access token with selected permissions from Github app ... installed on org 

inputs:
  app_id:
    required: true
  app_private_key:
    required: true
  app_installation_id:
    required: true
  permissions:
    description: "Comma separated list of permissions, e.g. contents:write,issues:read."
    required: false

outputs:
  token:
    description: "App installation access token"
    value: ${{ steps.generate_token.outputs.result }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        path: tmp
  
    - name: Install dependencies
      shell: bash
      run: npm install @octokit/auth-app @octokit/rest

    - name: Generate Github app installation token
      id: generate_token
      uses: actions/github-script@v6
      env:
        APPLICATION_ID: ${{ inputs.app_id }}
        APPLICATION_PRIVATE_KEY: ${{ inputs.app_private_key }}
        APPLICATION_INSTALLATION_ID: ${{ inputs.app_installation_id }}
        REPOSITORY_ID: ${{ github.repository_id }}
      with:
        script: |            
          const { Octokit } = require("@octokit/rest");
          const { createAppAuth } = require("@octokit/auth-app");

          const appOctokit = new Octokit({
            authStrategy: createAppAuth,
            auth: {
              appId: process.env.APPLICATION_ID,
              privateKey: process.env.APPLICATION_PRIVATE_KEY,
              installationId: process.env.APPLICATION_INSTALLATION_ID
            },
            request: {
              fetch: fetch,
            }
          });

          const { data } = await appOctokit.request("/app");
          console.log(data);

          appOctokit.auth({
            type: "app"
          });

          const { token } = await appOctokit.request("POST /app/installations/{installation_id}/access_tokens", {
            installation_id: process.env.APPLICATION_INSTALLATION_ID,
            repository: "test",
            permissions: {
              contents: "read"
            }
          })
          console.log(token);

    # - name: Get token
    #   shell: bash
    #  run: echo "${{steps.generate_token.outputs.result}}"

    #          const { test } = await appOctokit.checkToken({
    #        "Iv1.7e6dbb80944977a9",
    #        token.token
    #      });
    #      console.log(test);
