name: 'Hello World'
description: 'Greet someone'

inputs:
  parameter1:  # id of input
    description: 'Description'
    required: true

runs:
  using: "composite"
  steps:
    - name: Step 1
      shell: bash
      run: echo "test"
    - name: Step 2
      if: ${{ inputs.parameter1 == 'true' }}
      shell: bash
      run: echo "test"
    - name: Run action
      uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a
