name: 'Hello World'
description: 'Greet someone'
runs:
  using: "composite"
  steps:
    - name: Step 1
      shell: bash
      run: echo "test"
    - name: Step 2
      shell: bash
      run: echo "test"
