name: "Testing"

on:
  check_run:
    types: [ created, rerequested, completed, requested_action ]

jobs:
  check_run:
    name: Check run
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: echo "${{ toJSON(github.event) }}"
