name: Calling workflow Auto merge

on:
  push:
    branches: main

jobs:
  get_app_token:
    runs-on: ubuntu-latest
    steps:
      - run: npm install @octokit/auth-app @octokit/rest
      - uses: actions/github-script@v6
        env:
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          APPLICATION_PRIVATE_KEY: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          APPLICATION_INSTALLATION_ID: ${{ secrets.APPLICATION_INSTALLATION_ID }}
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            const { createAppAuth } = require("@octokit/auth-app");

            const appOctokit = new Octokit({
              authStrategy: createAppAuth,
              auth: {
                appId: process.env.APPLICATION_ID,
                privateKey: process.env.APPLICATION_PRIVATE_KEY,
                installationId: process.env.APPLICATION_INSTALLATION_ID
              },
            });

            const { token } = await appOctokit.auth({
              type: "installation"
            });
