name: Calling workflow Auto merge

on:
  push:
    branches: main

jobs:
  get_app_token:
    runs-on: ubuntu-latest
    steps:
      - run: npm install @octokit/auth-app
      - uses: actions/github-script@v6
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            const { createAppAuth } = require("@octokit/auth-app");

            const appOctokit = new Octokit({
              authStrategy: createAppAuth,
              auth: {
                appId: 123,
                privateKey: process.env.PRIVATE_KEY,
                // optional: this will make appOctokit authenticate as app (JWT)
                //           or installation (access token), depending on the request URL
                installationId: 123,
              },
            });
