name: Calling workflow Auto merge

on:
  push:
    branches: main

jobs:
  get_app_token:
    runs-on: ubuntu-latest
    steps:
      - name: Generate app token
        id: generate_token
        uses: mrmxyzptlk1/test/.github/actions/generate_app_token@main
        with:
          app_id: ${{ secrets.APPLICATION_ID }}
          app_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          app_installation_id: ${{ secrets.APPLICATION_INSTALLATION_ID }}
          permissions: "contents: write, administration:write"

      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Create environment with github-script
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            github.rest.repos.createOrUpdateEnvironment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment_name: 'test',
              wait_timer: 1
            })
