name: Calling workflow Auto merge

on:
  push:
    branches: main

jobs:
  get_app_token:
    runs-on: ubuntu-latest
    steps:
      - run: npm install @octokit/auth-app @octokit/rest
      - uses: actions/github-script@v6
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            const { createAppAuth } = require("@octokit/auth-app");

            const appOctokit = new Octokit({
              authStrategy: createAppAuth,
              auth: {
                appId: ${{ secrets.APPLICATION_ID }},
                privateKey: ${{ secrets.APPLICATION_PRIVATE_KEY }},
                installationId: ${{ secrets.APPLICATION_INSTALLATION_ID }}
              },
            });
