name: Calling workflow Auto merge

on:
  push:
    branches: main

jobs:
  get_app_token:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run:  |
          echo ${{ fromJSON(toJSON(vars)).VAR_ONE }}
          echo ${{ fromJSON(toJSON(vars)).VAR_TWO }}
      #- name: Generate app token
      #  id: generate_token
      #  uses: mrmxyzptlk1/test/.github/actions/generate_app_token@main
      #  with:
      #    app_id: ${{ secrets.APPLICATION_ID }}
      #    app_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
      #    app_installation_id: ${{ secrets.APPLICATION_INSTALLATION_ID }}
      #    permissions: "contents: write, administration: write"

      #- uses: actions/checkout@v3
      #  with:
      #    token: ${{ steps.generate_token.outputs.token }}

      #- name: Check with curl
      #  shell: bash
      #  run: |
      #    curl -L \
      #    -X PUT \
      #    -H "Accept: application/vnd.github+json" \
      #    -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
      #    -H "X-GitHub-Api-Version: 2022-11-28" \
      #    https://api.github.com/repos/mrmxyzptlk1/test/environments/test \
      #    -d '{"wait_timer":1}'
