name: "Issue comment edited"

on:
  issue_comment:
    types: [edited]

jobs:
  issue_comment_edited:
    name: Issue comment edited
    runs-on: ubuntu-latest
    steps:
      - name: Check comment body
        run: echo "${{ github.event.comment.body }}"

      - name: Check conditions
        run: |
          echo "${{ startsWith( github.event.comment.body, "Test comment:" ) }}"
          echo "${{ contains( github.event.comment.body, "[x]" ) }}"
          echo "${{ startsWith( github.event.comment.body, "Test comment:" ) && contains( github.event.comment.body, "[x]" ) }}"
