name: "Issue comment edited"

on:
  issue_comment:
    types: [edited]

jobs:
  create_comment:
    if: github.event_name == 'issue_comment'
    runs-on: ubuntu-latest
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find_comment
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Automatic PR merge process:'
  
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Automatic PR merge process:

            - For automatic PR merge use **Enable auto-merge (squash)** button below or
            - [ ] Select the checkbox to force PR merge
          edit-mode: replace

  issue_comment_edited:
    if: |
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, 'Automatic PR merge process:') &&
      contains(github.event.comment.body, '- [x] Select')
    name: Issue comment edited
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Set status
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/scripts/set_status_check.js');
            await script({github, context});
