name: "Issue comment edited"

on:
  issue_comment:
    types: [edited]

jobs:
  issue_comment_edited:
    if: startsWith( '${{ github.event.comment.body }}', 'Test comment:' ) && contains( '${{ github.event.comment.body }}', '[x]' )
    name: Issue comment edited
    runs-on: ubuntu-latest
    env:
      BODY: "${{ github.event.comment.body }}"
    steps:
      - name: Check comment body
        run: echo "${{ env.BODY }}"

      - name: Check conditions
        run: |
          echo "${{ startsWith( env.BODY, 'Test comment:' ) }}"
          echo "${{ contains( env.BODY, '[x]' ) }}"
          echo "${{ startsWith( env.BODY, 'Test comment:' ) && contains( env.BODY, '[x]' ) }}"
