name: "Issue comment edited"

on:
  issue_comment:
    types: [edited]

jobs:
  get_sha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Set status
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/scripts/set_status_check.js');
            await script({core, fetch});

  issue_comment_edited:
    if: |
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, 'Automatic PR merge process:') &&
      contains(github.event.comment.body, '- [x] Select')
    name: Issue comment edited
    runs-on: ubuntu-latest
    env:
      BODY: "${{ github.event.comment.body }}"
    steps:
      - name: Check comment body
        run: echo "${{ env.BODY }}"

      - name: Check conditions
        run: |
          echo "${{ startsWith( env.BODY, 'Test comment:' ) }}"
          echo "${{ contains( env.BODY, '[x]' ) }}"
          echo "${{ startsWith( env.BODY, 'Test comment:' ) && contains( env.BODY, '[x]' ) }}"

      - name: Check 1
        if: "${{ startsWith( env.BODY, 'Test comment:' ) && contains( env.BODY, '[x]' ) }}"
        run: echo "check 1"

      - name: Other check
        run: |
          echo "${{ startsWith( github.event.comment.body, 'Test comment:' ) }}"
          echo "${{ contains( github.event.comment.body, '[x]' ) }}"
          echo "${{ startsWith(github.event.comment.body, 'Automatic PR merge process:') && contains(github.event.comment.body, '- [x] Select') }}"
