name: "Issue comment edited"

on:
  issue_comment:
    types: [edited]

jobs:
  get_sha:
    runs-on: ubuntu-latest
    steps:
      - name: Get sha
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            const ref = data.head.sha;
            console.log(ref);
            
            const { data } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: ref,
            });
            console.log(data);
            console.log(data.check_runs.find(({ name }) => name === 'test')?.id);
            const check_run_id = data.check_runs.find(({ name }) => name === 'test')?.id
            console.log(check_run_id);

  issue_comment_edited:
    if: |
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, 'Automatic PR merge process:') &&
      contains(github.event.comment.body, '- [x] Select')
    name: Issue comment edited
    runs-on: ubuntu-latest
    env:
      BODY: "${{ github.event.comment.body }}"
    steps:
      - name: Check comment body
        run: echo "${{ env.BODY }}"

      - name: Check conditions
        run: |
          echo "${{ startsWith( env.BODY, 'Test comment:' ) }}"
          echo "${{ contains( env.BODY, '[x]' ) }}"
          echo "${{ startsWith( env.BODY, 'Test comment:' ) && contains( env.BODY, '[x]' ) }}"

      - name: Check 1
        if: "${{ startsWith( env.BODY, 'Test comment:' ) && contains( env.BODY, '[x]' ) }}"
        run: echo "check 1"

      - name: Other check
        run: |
          echo "${{ startsWith( github.event.comment.body, 'Test comment:' ) }}"
          echo "${{ contains( github.event.comment.body, '[x]' ) }}"
          echo "${{ startsWith(github.event.comment.body, 'Automatic PR merge process:') && contains(github.event.comment.body, '- [x] Select') }}"
