name: "Pull request"

on:
  pull_request:
    types: [ edited ]

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - name: Check comment
        uses: actions/github-script@v6
        with:
          script: |
            const comment = context.payload.pull_request.body;
            console.log(comment);
            console.log("next");
            const changes = context.payload.changes;
            console.log(changes);
    
      - name: Body
        run: echo "${{ toJSON(github.event.pull_request.body) }}"

