name: "Pull request"

on:
  pull_request:
    types: [ synchronize ]

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const test = ${{ '[test]' != '[]' && 0 || 0 }};
            console.log(test);
            console.log(typeof test);
