name: "Run composite action"

on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: "true"
          PR_FILTER: "auto_merge"
