name: "PR merging"

on:
  pull_request:
    types: [ auto_merge_enabled ]

jobs:
  context_info:
    name: Context info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Echo context
        run: |
          echo ${{ toJson(github.event) }}
    
      - name: Update pull request branch
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.updateBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              expected_head_sha: context.payload.pull_request.head.sha
            });

      - name: Check mergability
        run: |
          if git merge-base --is-ancestor main @
            then
              echo "Your branch is up to date."
              exit 0
            else
              echo "You need to merge / rebase."
              exit 1
            fi
      
      - name: Check
        run: git diff $(git merge-base main)
