name: "Pull request"

on:
  pull_request:
    types: [ edited ]

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - name: If PR title change
        if: ${{ toJSON(github.event.changes.title) }} != null
        run: echo "test"

      - name: If PR body change
        if: ${{ toJSON(github.event.changes.body) }} != null
        run: echo "${{ toJSON(github.event.changes.body) }}"

      - name: Echo
        run: |
          echo "${{ toJSON(github.event.changes) }}"
          echo "${{ toJSON(github.event.changes.base) }}"
          echo "${{ toJSON(github.event.changes.body) }}"
          echo "${{ toJSON(github.event.changes.title) }}"
    
      - name: Skip
        if: contains(github.event.pull_request.body, format('- [x] {0}', 'deploy'))
        run: echo "test"
    
      - name: Check comment
        uses: actions/github-script@v6
        with:
          script: |
            const pr_body = `<details><summary>Test</summary>

            <details><summary>Apps</summary>
            
            - [ ] app1
            - [ ] app2
            
            </details>
            
            <details><summary>Environments</summary>
            
            - [ ] env1
            - [ ] env2
            
            </details>
            
            <details><summary>Command</summary>
            
            - [ ] command1
            - [ ] command2
            
            </details>
            
            </details>`
            
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              body: pr_body
            });
    
      - name: Check comment
        uses: actions/github-script@v6
        with:
          script: |
            const comment = `context.payload.pull_request.body`;
            console.log(comment);
            console.log("next");
            res = comment.match(/^(- [x])$/mg);
            console.log(res);
            const changes = context.payload.changes;
            console.log(changes);
    
      - name: Body
        run: echo "${{ toJSON(github.event.pull_request.body) }}"

