name: "Run composite action"

on:
  pull_request:
    types: [labeled]

jobs:
  check:
    name: Check email
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(github.event.sender) }}"
