name: "Test filtering"

on:
  pull_request:
    types: [ synchronize, auto_merge_enabled, auto_merge_disabled ]
  issue_comment:
    types: [edited]

env:
  COMMENT: '- [x] ${{ vars.COMMENT_TEST }}'

concurrency:
  #group: ${{ github.event.number }}-${{ contains(fromJSON('["auto_merge_enabled", "auto_merge_disabled"]'), github.event.action) }}
  group: ${{ contains(fromJSON('["auto_merge_enabled", "auto_merge_disabled"]'), github.event.action) && github.event.number || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"