name: "Run composite action"

on:
  push:

jobs:
  composite_action:
    name: Composite action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Invoke my action
        uses: ./.github/composite_actions/push_to_main
