name: "Pull request"

on:
  pull_request:
    types: [ synchronize ]

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
        id: filter
        with:
          filters: |
            folder1:
              - folder1/**
              - folder3/**
              - folder1/!(tests)/**
              - folder3/!(tests)/**
              - folder4/**
              - folder5/**
            folder2:
              - folder2/**
              - folder3/**
              - folder2/!(tests)/**
              - folder3/!(tests)/**
              - folder4/**
              - folder5/**
