name: "Pull request"

on:
  pull_request:
    types: [ edited ]

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - name: Changes
        run: echo "${{ toJSON(github.event.changes) }}"

      - name: Body
        run: echo "${{ toJSON(github.event.pull_request.body) }}"
