name: "Pull request 2"

on:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]

jobs:
  job2:
    if: github.event.action != 'edited'
    name: Job2
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "step 1"

  job3:
    if: github.event.action != 'edited'
    needs: job2
    name: Job3
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: exit 1

  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "step 1"
