name: "Pull request"

on:
  pull_request:
    types: [ edited ]

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "${{ toJSON(github.event) }}"
