name: "Run composite action"

on:
  push:

jobs:
  check:
    name: Check email
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: actions/github-script@v6
        with:
          script: |
            const data = github.rest.users.listPublicEmailsForAuthenticated();
            console.log(data);
