name: "PR merging"

on:
  pull_request:
    types: [ synchronize ]

jobs:
  merge_conflict:
    name: Merge conflicts
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Update pull request branch
        uses: actions/github-script@v6
        with:
          script: |
            var { data } = await github.rest.repos.compareCommitsWithBasehead({
              owner: context.repo.owner,
              repo: context.repo.repo,
              basehead: '${{ github.base_ref }}...${{ github.head_ref }}'
            });
            console.log(data);
            console.log(data.behind_by);

            if (data.behind_by > 0) {
              github.rest.pulls.updateBranch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                expected_head_sha: context.payload.pull_request.head.sha
              });
            }
