name: "Run composite action"

on:
  push:

jobs:
  composite_action:
    name: Composite action
    runs-on: ubuntu-latest
    steps:
      - name: Invoke my action
        uses: ./test/actions/push_to_main
        with:
          parameter1: 'true'

      - uses: actions/checkout@v3
