name: "Test filtering"

on:
  pull_request:

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
      environment: ${{ steps.env_name.outputs.environment }}
    steps:
      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
        id: filter
        with:
          filters: |
            folder_one:
              - "folder1/**"
            folder_two:
              - "folder2/**"

      - if: steps.filter.outputs.changes != '[]'
        id: env_name
        run: echo "environment=PR #${{ github.event.number }}" >> "$GITHUB_OUTPUT"

  test:
    name: test
    needs: changes
    runs-on: ubuntu-latest
    environment: ${{ needs.changes.outputs.environment }}
    steps:
      - if: fromJSON(!contains(fromJSON('["auto_merge_enabled, auto_merge_disabled"]'), github.event.action)) &&
            needs.changes.outputs.changes != '[]'
        name: Test condition
        run: echo "pass"
    
      #- uses: docker://chinthakagodawita/autoupdate-action:v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    DRY_RUN: "true"
      #    PR_FILTER: "auto_merge"
