name: "Test filtering"

on:
  pull_request:
  issue_comment:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      #- name: Generate app token
      #  id: generate_token
      #  uses: mrmxyzptlk1/test/.github/actions/generate_app_token@main
      #  with:
      #    app_id: ${{ secrets.APPLICATION_ID }}
      #    app_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
      #    app_installation_id: ${{ secrets.APPLICATION_INSTALLATION_ID }}
      #    permissions: "administration:write"
    
      - name: Test
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed("Set exit code");
            process.exit();
            console.log("test");
      
      #- name: Delete environment
      #  uses: actions/github-script@v6
      #  with:
      #    github-token: ${{ steps.generate_token.outputs.token }}
      #    script: |
      #      try {
      #        response = await github.rest.repos.deleteAnEnvironment({
      #          owner: context.repo.owner,
      #          repo: context.repo.repo,
      #          environment_name: 'test'
      #        });
      #      } catch (error) {
      #        if (error.status == 404) {
      #          console.log("Environment does not exist.");
      #        } else {
      #          throw error
      #        }
      #      }
