name: Called workflow Auto merge

on:
  workflow_dispatch:

jobs:
  detect_change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            github.rest.repos.createOrUpdateEnvironment({
              owner: 'mrmxyzptlk1',
              repo: 'test',
              environment_name: 'PR #2',
              wait_timer: 1
            })

  auto_merge:
    needs: detect_change
    runs-on: ubuntu-latest
    environment: 'PR #2'
    steps:
      - run: echo "auto_merge!"
