name: "Called workflow"

on:
  workflow_call:

jobs:
  status_check_one:
    if: github.event.action != 'synchronize'
    name: Status check one
    runs-on: ubuntu-latest
    steps:
      - run: echo "check"
  
