name: Check app token

on:
  pull_request:
    types: [labeled]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: list repos accessible to token
        run: gh api /installation/repositories --paginate --jq .repositories.[].full_name
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ steps.get_workflow_token.outputs.token }}

     # - name: Create test file
     #   run: date +%s > test.txt

     # - name: Add and commit
     #   uses: EndBug/add-and-commit@72e246094f1af94def5a07467cd789c503ae8be0
     #   with:
     #     default_author: github_actions
