name: "Repository dispatch"

on:
  repository_dispatch:
    types: [synchronize]

jobs:
  workflow_run:
    name: Second workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check context
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context.payload.client_payload.pull_request.number);
            console.log(context.payload.client_payload.pull_request.head.ref);
            console.log(context.payload.client_payload.pull_request.head.sha);
    
      - name: Check event object
        run: |
          echo "${{ github.event.client_payload.number }}"
          echo "${{ github.event.client_payload.pull_request.head.ref }}"
          echo "${{ github.event.client_payload.pull_request.head.sha }}"

      - name: Check pr object
        run: echo "'${{ toJSON(github.event.client_payload.pull_request) }}'"
      
      - name: Check whole event object
        run: echo ${{ toJSON(github.event) }}
