name: "Status check"

# The workflow to execute on is comments that are newly created
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  status_check_one:
    if: false
    name: Status check one
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
