name: "Status check"

# The workflow to execute on is comments that are newly created
on:
  pull_request:
    types: [created, edited, syncronize]

jobs:
  status_check_one:
    uses: ./.github/workflows/on_workflow_call.yml
