name: "Status check"

# The workflow to execute on is comments that are newly created
on:
  pull_request:
    types: [created, edited, synchronize]

jobs:
  status_check_one:
    if: github.event.action != 'synchronize'
    uses: ./.github/workflows/on_workflow_call.yml
