name: "branch deploy demo"

# The workflow to execute on is comments that are newly created
on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: write

jobs:
  demo:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: github/branch-deploy@v7.5.1
        id: branch-deploy
        with:
          noop_trigger: test

      - run: echo ${{ steps.branch-deploy.outputs.ref }}
