name: "Commit with app"

on:
  pull_request:
    types: [labeled]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Generate app token
        id: generate_token
        uses: mrmxyzptlk1/test/.github/actions/generate_app_token@main
        with:
          app_id: ${{ secrets.APPLICATION_ID }}
          app_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          app_installation_id: ${{ secrets.APPLICATION_INSTALLATION_ID }}
          permissions: "contents:write"
    
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Create report file
        run: date +%s > report.txt

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: ghapp-mrmxyzptlk1[bot]
          commit_user_email: 148899933+ghapp-mrmxyzptlk1[bot]
          commit_author: ghapp-mrmxyzptlk1[bot]
